/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

type ErrorWithCode = Error & { code: number }
type MaybeErrorWithCode = ErrorWithCode | null | undefined

const createErrorFromCodeLookup: Map<number, () => ErrorWithCode> = new Map()
const createErrorFromNameLookup: Map<string, () => ErrorWithCode> = new Map()

/**
 * RelationAlreadyClosed: 'Closing relations twice is unsupported for now'
 *
 * @category Errors
 * @category generated
 */
export class RelationAlreadyClosedError extends Error {
  readonly code: number = 0x1770
  readonly name: string = 'RelationAlreadyClosed'
  constructor() {
    super('Closing relations twice is unsupported for now')
    if (typeof Error.captureStackTrace === 'function') {
      Error.captureStackTrace(this, RelationAlreadyClosedError)
    }
  }
}

createErrorFromCodeLookup.set(0x1770, () => new RelationAlreadyClosedError())
createErrorFromNameLookup.set(
  'RelationAlreadyClosed',
  () => new RelationAlreadyClosedError()
)

/**
 * Overflow: 'Overflow occured'
 *
 * @category Errors
 * @category generated
 */
export class OverflowError extends Error {
  readonly code: number = 0x1771
  readonly name: string = 'Overflow'
  constructor() {
    super('Overflow occured')
    if (typeof Error.captureStackTrace === 'function') {
      Error.captureStackTrace(this, OverflowError)
    }
  }
}

createErrorFromCodeLookup.set(0x1771, () => new OverflowError())
createErrorFromNameLookup.set('Overflow', () => new OverflowError())

/**
 * Attempts to resolve a custom program error from the provided error code.
 * @category Errors
 * @category generated
 */
export function errorFromCode(code: number): MaybeErrorWithCode {
  const createError = createErrorFromCodeLookup.get(code)
  return createError != null ? createError() : null
}

/**
 * Attempts to resolve a custom program error from the provided error name, i.e. 'Unauthorized'.
 * @category Errors
 * @category generated
 */
export function errorFromName(name: string): MaybeErrorWithCode {
  const createError = createErrorFromNameLookup.get(name)
  return createError != null ? createError() : null
}
